### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by lynchlee** [imvicchen/victheme-Wordpress-Theme#1]
我在本地试装了一下，发现
1. 下面的微信，微博那一栏显示不出来图标，是什么问题呢？
2. 网站Logo在哪换？

请教一下以上问题，多谢、

**Comment by imvicchen** [comment]
logo 需要从代码手动替换 或者 替换 img/logo@2x.png 尺寸是150*40
图标不显示 这个不确定 可能是浏览器支持问题 也可能是因为图标字体文件的问题 需要排查

**Comment by lynchlee** [comment]
@imvicchen 好的。多谢！

**Comment by imvicchen** [comment]
@lynchlee 不客气，有问题来提

**Comment by lynchlee** [comment]
昨天新发现：用域名访问站点的时候 微信、微博、github、腾讯微博那几个图标显示成小方块儿，用IP访问的时候就显示正常没问题。

**Comment by imvicchen** [comment]
@lynchlee 方便提供下域名吗

**Comment by lynchlee** [comment]
@imvicchen http://kenshinn.net http://23.106.141.199/

**Comment by lynchlee** [comment]
@imvicchen 啊 处理好了，之前站点地址用的ip，我都换成域名就可以了。 多谢。！
